export type DomainErrorCode =
  | "battle_not_found"
  | "unit_not_found"
  | "target_not_found"
  | "not_active_unit"
  | "tile_not_found"
  | "same_position"
  | "destination_unreachable"
  | "initiative_invalid"
  | "attacker_defeated"
  | "target_defeated"
  | "friendly_target"
  | "attack_out_of_range"
  | "main_action_unavailable"
  | "ability_not_known"
  | "ability_target_required"
  | "ability_target_invalid"
  | "ability_out_of_range"
  | "ability_no_targets"
  | "ability_no_effect"
  | "noble_phantasm_unavailable"
  | "noble_phantasm_target_invalid"
  | "noble_phantasm_not_ready"
  | "noble_phantasm_out_of_range"
  | "contract_not_found"
  | "master_defeated"
  | "servant_defeated"
  | "master_not_active"
  | "contract_out_of_range"
  | "insufficient_mana"
  | "servant_mana_full"
  | "command_seals_exhausted"
  | "command_seal_no_effect"
  | "recall_destination_unavailable"
  | "scenario_not_active"
  | "scenario_already_started"
  | "scenario_completed"
  | "retreat_unavailable"
  | "strategy_not_active"
  | "strategy_action_points_exhausted"
  | "strategy_region_not_connected"
  | "strategy_region_not_discovered"
  | "strategy_region_already_investigated"
  | "strategy_leyline_unavailable"
  | "strategy_leyline_already_controlled"
  | "strategy_rest_unavailable"
  | "strategy_encounter_unavailable";

export interface DomainError {
  readonly code: DomainErrorCode;
  readonly message: string;
}
